Repository FromDoppler/doppler-jenkins-swarm, pull requests merged in 2023-04, with the labels that each got.

#23 fix: update docker login
  host-setup/docker/config.encrypted.secret.shared.json
Labels: size/S

#30 chore: shutdown test Jenkins test instance
  jenkins-stack/docker-compose.yml
  jenkins-stack/prod.env
  jenkins-stack/test.env
Labels: size/XS

#31 fix: startup jenkins prod instance
  jenkins-stack/prod.env
Labels: size/XS

#33 Create jobs for MakingSense Organization
  cspell-project-words.txt
  host-setup/ssh/known_hosts
  jenkins-stack/casc_configs/jenkins-base.template.yaml
  jenkins-stack/casc_configs/jenkins-prod.encrypted.secret.shared.yaml
  jenkins-stack/docker-compose.yml
  jenkins-stack/prod.env
  jenkins-stack/test.env
Labels: size/L

#34 fix: add EncryptionSettings env variables
  jenkins-stack/casc_configs/jenkins-base.encrypted.secret.shared.yaml
Labels: size/M

#35 chore: add credential for fromdoppler github packages
  jenkins-stack/casc_configs/jenkins-base.encrypted.secret.shared.yaml
Labels: size/M

#37 Support PRs from forks
  cspell-project-words.txt
  jenkins-stack/casc_configs/jenkins-base.template.yaml
  jenkins-stack/docker-compose.yml
Labels: size/M

#39 feat: build tags
  jenkins-stack/casc_configs/jenkins-base.template.yaml
Labels: size/XS

#40 chore: add admin user
  cspell-project-words.txt
  jenkins-stack/casc_configs/jenkins-base.template.yaml
Labels: size/XS

#45 docs: add a caution note about organization scans after jobs recreation
  README.md
Labels: size/XS

#46 fix: map aws credentials
  jenkins-stack/docker-compose.yml
Labels: size/XS

#48 Shutdown test instance
  jenkins-stack/test.env
Labels: size/XS

#49 Improve docker prune
  cronjob-stack/docker-compose.yml
Labels: size/S
